owner: ros-2
repo: upptime-quickler

sites:
  - name: Quickler Dashboard
    url: https://app.quickler.co/healthz
    expectedStatusCodes:
      - 200
  - name: Quickler Engine
    url: https://reports.quickler.co/health
    expectedStatusCodes:
      - 200
  - name: Quickler Website
    url: https://quickler.co
    expectedStatusCodes:
      - 200

status-website:
  cname: status.quickler.co
  name: Quickler Status
  theme: light
  introTitle: "Quickler system status"
  introMessage: "Current and historical uptime for Quickler services."
  navbar:
    - title: Quickler
      href: https://quickler.co

notifications:
  - type: email
    address: philip@quickler.co

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  updates: "0 0 * * *"
  graphs: "0 0 * * *"
  staticSite: "0 0 * * *"
  summary: "0 0 * * *"

commitMessages:
  readmeContent: ":robot: Update README [skip ci]"
  statusChange: ":warning: $SITE_NAME is $STATUS"
  graphsUpdate: ":chart_with_upwards_trend: Update graphs [skip ci]"

i18n:
  activeIncidents: Active incidents
  allSystemsOperational: All systems operational
  incidentReport: Incident report for $SITE_NAME
  activeIncidentsDescription: We are currently investigating issues.
  noIncidentsDescription: No incidents have been reported.
